### ISSUE TITLE
None of the tutorial steps HTML have a link to deploy action anymore

### ISSUE THREAD

**Issue by ekharlamov** [ot4i/iib-tutorials#10]
When I select any tutorial now the Prepare tab does not have a button to deploy the tutorial BAR anymore!

**Comment by cathyyoung** [comment]
@ekharlamov Hi Eugene - we removed these after feedback from Alasdair. All these tutorials use the Flow exerciser which deploys the artifacts anyway, so it seemed redundant to make the user manually deploy them first. The deploy action is now optional and can be included for other tutorials if needed.
