### ISSUE TITLE
Not clear how to build this repo - master and gh-pages versions of repo_metadata out of sync

### ISSUE THREAD

**Issue by ajpaton** [ot4i/iib-tutorials#33]
As I understand it, the master branch for this repo contains all the source required to generate the working image.  However the working catalog of tutorials is served up from the gh-pages branch (particularly by the en/repo_metadata.json file).

At the moment, the content of repo_metadata.json in the master and gh-pages branches has diverged.  We could merge any changes from gh-pages back into master and use a build process to regenerate consistent source, but it's not clear how to do that.  Suggest that we update this repo to say how to build it (at least) so it's clear how gh-pages updates should be made.

**Comment by ajpaton** [comment]
I have submitted a pull request to master branch which brings repo_metadata in sync with the latest updates to the gh-pages branch.

**Comment by bthomps** [comment]
As discussed just now, build processes have changed since this issue was raised. Housekeeping so closing this issue off.
