### ISSUE TITLE
Should make it clear which tutorials require a v10 fixpack

### ISSUE THREAD

**Issue by ajpaton** [ot4i/iib-tutorials#34]
At the moment it is not clear which tutorials require the end user to install a later fixpack of Integration Bus.
Suggest that each tutorial should have in its brief description (which you get when clicking on its name) whether it requires a particular fixpack level.  There are a few like this:
- callable flows needs FP4
- BTM needs FP3
- calling Global Cache from a map needs FP2
  Should also update the details.html for each of those individual tutorials to say this, which the Global Cache one already does but the others do not.

**Comment by ajpaton** [comment]
I have just submitted a pull request to fix this, issue.

**Comment by bthomps** [comment]
This issue can now be closed - individual tutorials display the relevant fix pack level.
