### ISSUE TITLE
Suggestion re the heading text shown

### ISSUE THREAD

**Issue by tomwaterton** [ot4i/iib-tutorials#8]
Currently, when you open the Tutorial Gallery, this is the text that is displayed: 

**Show Me**
Here you can explore and learn about IBM Integration Bus using tutorials. 
What are you interested in? 

1) I'm not convinced that "Show Me" is the best title here. Why not use "Tutorial Gallery" so that it is really obvious to customers that this is where they are. 
(p.s. I see that the Eclipse tab is currently called "Tutorials Gallery" - but I don't think that the plural "s" is necessary. We normally speak of a "picture gallery", not of a "pictures gallery".)

2) In terms of the text underneath the heading, I think that the first line could be sharper and that the second line could be omitted altogether, as it does not really add anything. 

So, here is my suggestion:

**Tutorial Gallery**
Learn about core IBM Integration Bus concepts and explore key capabilities by running the following tutorials.

**Comment by bthomps** [comment]
Thanks for the comments Tom, and apologies this response has been so long in coming. I'm going to take this feedback on board for our next major version release.  Given this will involve a bunch of other work and some restructuring repos, I'm closing down this issue with this comment, but please don't interpret this as not acting on the feedback.  Cheers, Ben
